"""Shared palette, Plotly template, and figure helpers for 01_data_insights.ipynb.

The color constants mirror the swatches in docs/style.css. Site figures are
built bare and take their titles from index.html; titled() puts titles back on
for the PNGs in figures/.
"""

import json
from pathlib import Path

import plotly.graph_objects as go

SERIF, SANS, BG = "Newsreader", "IBM Plex Sans", "white"

# Colour reference: https://www.datawrapper.de/blog/colors-for-data-vis-style-guides

LEAD, ALT = "#733D47", "#D1A830"          # United States, China
UK_C, CA_C, DE_C = "#448DD4", "#4E8C7B", "#AA5D28"

FAINT = "#8C9495"  # unlabelled scatter markers, Pew's neutral gray row

MAP_SCALE = ["#E8EAD6", "#D2D995", "#B8C670", "#9EB353", "#84A03D",
             "#6B8D2B", "#537920", "#3E661C", "#2F511E", "#2E392C"]

GRID = "#F0F0F0"  # chart gridlines
PAD = 48          # left inset for PNG title blocks, matching the site's text column

HOVER = dict(bgcolor="white",
             bordercolor="rgba(0, 0, 0, 0.1)",
             font=dict(family=SANS, size=12, color="black"))

AXIS_DEFAULTS = dict(gridcolor="white", linecolor="white", ticks="", zerolinecolor="white",
                     zerolinewidth=2, automargin=True, title=dict(standoff=15))

SITE_TEMPLATE = dict(layout=dict(
    autotypenumbers="strict", hovermode="closest", font=dict(color="#2a3f5f"),
    hoverlabel=dict(align="left"), paper_bgcolor="white", plot_bgcolor="#E5ECF6",
    geo=dict(subunitcolor="white", showland=True, showlakes=True, lakecolor="white"),
    xaxis=AXIS_DEFAULTS, yaxis=AXIS_DEFAULTS,
))

def titled(fig, title, subtitle, legend=None, png=None, height=600, margin=None, title_top=26):
    """
    Add title/subtitle/legend back onto bare site figures, for display and figures/PNGs.
    The block sits flush left above the plot, the way index.html lays it out.

    """
    width = 800
    out = go.Figure(fig).update_layout(
        width=width, height=height, autosize=False, margin=margin,
        title=dict(
            x=PAD / width, xref="container", xanchor="left", y=1 - title_top / height, yanchor="top",
            font=dict(family=SANS, size=18, color="black"),
            # <b> on title
            text=f"<b>{title}</b><br><span style='font-family:{SERIF};font-size:13px'>{subtitle}</span>",
        ),
    )
    if legend:
        # Annotations take paper coordinates only. Convert from pixels;
        # 48px under the title puts the legend below the subtitle, as index.html has it
        left, right = out.layout.margin.l, out.layout.margin.r
        plot_height = height - out.layout.margin.t - out.layout.margin.b
        out.add_annotation(
            x=(PAD - left) / (width - left - right),
            y=(height - out.layout.margin.b - title_top - 48) / plot_height,
            xref="paper", yref="paper", xanchor="left", showarrow=False,
            font=dict(family=SANS, size=12, color="black"),
            text="&nbsp;&nbsp;&nbsp;&nbsp;".join(
                f"<span style='color:{color}'>●</span> {label}" for label, color in legend),
        )
    if png:
        out.write_image(f"../figures/{png}")
    return out

def write_chart_data(charts, path="../docs/js/chart-data.js"):
    """
    Produces script with plotly specs (../docs/js/chart-data.js).

    """
    blocks = []
    for chart_id, fig in charts.items():
        spec = json.loads(fig.to_json())
        spec["layout"]["template"] = SITE_TEMPLATE
        traces = ",\n  ".join(json.dumps(trace) for trace in spec["data"])
        blocks.append(f'{{"id": "{chart_id}",\n "data": [\n  {traces}\n ],\n'
                      f' "layout": {json.dumps(spec["layout"], indent=2)}}}')
    Path(path).write_text(
        "/* Generated by notebooks/01_data_insights.ipynb.\n"
        "   Plotly specs for the four figures in index.html. */\n"
        "window.CHART_SPECS = [\n" + ",\n".join(blocks) + "\n];\n")
    print(f"wrote {path} ({Path(path).stat().st_size:,} bytes)")

def short_number(number):
    """
    Returns str: the short-form (K or M) of a long-form number (ex. 1000 becomes 1K).

    """

    for cutoff, suffix in ((1_000_000, "M"), (1_000, "K")):
        if abs(number) >= cutoff:
            scaled = number / cutoff
            return f"{int(scaled)}{suffix}" if scaled == int(scaled) else f"{round(scaled, 1)}{suffix}"
    return str(number)

def darken(hex_color, factor=0.72):
    """
    Returns str: hex_color scaled toward black (ex. 0.72 keeps 72% of each channel).

    """
    channels = (int(hex_color[i:i + 2], 16) for i in (1, 3, 5))
    return "#%02x%02x%02x" % tuple(int(c * factor) for c in channels)

def gradient_color(value, scale, low, high):
    """
    Get hex color for value in gradient
    """
    position = min(max((value - low) / (high - low), 0), 1) if high > low else 0.5
    index = min(int(position * (len(scale) - 1)), len(scale) - 2)
    fraction = position * (len(scale) - 1) - index
    start, end = (tuple(int(c[i:i + 2], 16) for i in (1, 3, 5)) for c in scale[index:index + 2])
    return "#%02x%02x%02x" % tuple(int(a + (b - a) * fraction) for a, b in zip(start, end))
